import { Peserta, Terapis, SlotHarian, BookingTerapi, PendaftaranAsesmenGuest, AdminUser } from '../types';

export const INITIAL_ADMINS: AdminUser[] = [
  {
    id: 'admin-1',
    nama: 'Sugeng',
    roleTitle: 'Admin 1 ULD Kota Probolinggo',
    pin: '990011',
    nomorTelepon: '6285236028521'
  },
  {
    id: 'admin-2',
    nama: 'Helmi',
    roleTitle: 'Admin 2 ULD Kota Probolinggo',
    pin: '990022',
    nomorTelepon: '6282247952696'
  }
];

export const INITIAL_TERAPIS: Terapis[] = [
  {
    id: 'terapis-1',
    nipOrId: 'TP-AHMAD-01',
    nama: 'Ahmad Hafizul Adly, S.Pd.',
    gelar: 'Terapis Perilaku (Behavior Therapist)',
    spesialisasi: 'terapis_perilaku',
    spesialisasiLabel: 'Terapis Perilaku',
    pin: '223344',
    nomorTelepon: '081234567891',
    deskripsi: 'Fokus intervensi perilaku terapan (ABA), pembiasaan instruksi, bina diri, dan modifikasi tantrum.',
    ruangPraktek: 'Ruang Terapi Perilaku & Sensori 1',
    isActive: true
  },
  {
    id: 'terapis-2',
    nipOrId: 'FT-INDARYATI-02',
    nama: 'Indaryati Machmudi, A.Md.Kes',
    gelar: 'Fisioterapis Pediatrik',
    spesialisasi: 'fisioterapis',
    spesialisasiLabel: 'Fisioterapis',
    pin: '445566',
    nomorTelepon: '081234567892',
    deskripsi: 'Spesialis stimulasi motorik kasar, latihan penguatan otot, postur, keseimbangan dinamis, dan fisioterapi.',
    ruangPraktek: 'Ruang Fisioterapi Gimnasium Inklusif',
    isActive: true
  },
  {
    id: 'terapis-3',
    nipOrId: 'PLB-SALMA-03',
    nama: 'Salma Salwa Salsabila, S.Pd.',
    gelar: 'Tenaga Pendidikan Luar Biasa (PLB)',
    spesialisasi: 'tenaga_plb',
    spesialisasiLabel: 'Tenaga PLB',
    pin: '334455',
    nomorTelepon: '081234567893',
    deskripsi: 'Bimbingan kesiapan sekolah inklusi, PPI individual, simbol visual alternatif, dan remedial pra-akademik.',
    ruangPraktek: 'Ruang Edukasi & Remedial PLB',
    isActive: true
  },
  {
    id: 'terapis-4',
    nipOrId: 'PSI-IKHSAN-04',
    nama: 'Muhammad Ikhsan, M.Psi., Psikolog',
    gelar: 'Psikolog',
    spesialisasi: 'psikolog',
    spesialisasiLabel: 'Psikolog',
    pin: '112233',
    nomorTelepon: '081234567894',
    deskripsi: 'Asesmen psikologis komprehensif, evaluasi kematangan tumbuh kembang, dan konseling keluarga disabilitas.',
    ruangPraktek: 'Ruang Konsultasi & Observasi Psikologi',
    isActive: true
  }
];

// Helper to format Date to YYYY-MM-DD in local time
export const formatLocalDate = (d: Date): string => {
  const yyyy = d.getFullYear();
  const mm = String(d.getMonth() + 1).padStart(2, '0');
  const dd = String(d.getDate()).padStart(2, '0');
  return `${yyyy}-${mm}-${dd}`;
};

// Helper to get only weekdays (Senin - Jumat)
export const getNextWeekdayDate = (dayOffset: number): string => {
  const d = new Date();
  // If current day is Saturday (6) or Sunday (0), advance to next Monday first
  while (d.getDay() === 0 || d.getDay() === 6) {
    d.setDate(d.getDate() + 1);
  }
  let added = 0;
  while (added < dayOffset) {
    d.setDate(d.getDate() + 1);
    const day = d.getDay(); // 0 is Sunday, 6 is Saturday
    if (day !== 0 && day !== 6) {
      added++;
    }
  }
  // Double-check: ensure it never falls on weekend
  while (d.getDay() === 0 || d.getDay() === 6) {
    d.setDate(d.getDate() + 1);
  }
  return formatLocalDate(d);
};

// 48 Siswa Terapi Rutin Kota Probolinggo (Dibersihkan dari data ganda & difilter khusus yang datang untuk terapi)
export const INITIAL_PESERTA: Peserta[] = [
  {
    id: 'peserta-01',
    nomorRekamMedis: 'ULD-PROB-2026-0001',
    namaLengkap: 'Abimanyu Tri Yoga',
    pin: '123456',
    tanggalLahir: '2016-04-12',
    jenisKelamin: 'L',
    namaWali: 'Endah Kurniawati',
    nomorTelepon: '085335389275',
    alamat: 'Jl. KH Mansur No. 92 B',
    kecamatan: 'Mayangan',
    asalSekolah: 'SDN Mangunharjo 10',
    ragamDisabilitas: 'Terapi Perilaku & Intervensi Belajar',
    status: 'aktif',
    terdaftarSejak: '2026-08-01',
    catatanKhusus: 'Kunjungan rutin terapi mingguan di ULD.',
    assignedTerapisId: 'terapis-1',
    assignedTerapisNama: 'Ahmad Hafizul Adly, S.Pd.',
    assignedAt: '2026-08-01'
  },
  {
    id: 'peserta-02',
    nomorRekamMedis: 'ULD-PROB-2026-0002',
    namaLengkap: 'Alfi Zafran P',
    pin: '123456',
    tanggalLahir: '2015-08-19',
    jenisKelamin: 'L',
    namaWali: 'Kusdiantoro',
    nomorTelepon: '085330892710',
    alamat: 'Jl. Pahlawan IV / 50',
    kecamatan: 'Kanigaran',
    asalSekolah: 'SLB Sinar Harapan 3',
    ragamDisabilitas: 'Terapi Motorik & Kognitif',
    status: 'aktif',
    terdaftarSejak: '2026-08-01',
    assignedTerapisId: 'terapis-2',
    assignedTerapisNama: 'Indaryati Machmudi, A.Md.Kes',
    assignedAt: '2026-08-01'
  },
  {
    id: 'peserta-03',
    nomorRekamMedis: 'ULD-PROB-2026-0003',
    namaLengkap: 'Aliando Hasbullah',
    pin: '123456',
    tanggalLahir: '2017-02-14',
    jenisKelamin: 'L',
    namaWali: 'Herina Dini / Rina Sulitiandini',
    nomorTelepon: '085604039610',
    alamat: 'Muneng / Jl. Raya Bromo',
    kecamatan: 'Luar Kota',
    asalSekolah: 'MI Syaiful Rizal',
    ragamDisabilitas: 'Terapi Perilaku & Wicara',
    status: 'aktif',
    terdaftarSejak: '2026-08-01',
    assignedTerapisId: 'terapis-1',
    assignedTerapisNama: 'Ahmad Hafizul Adly, S.Pd.',
    assignedAt: '2026-08-01'
  },
  {
    id: 'peserta-04',
    nomorRekamMedis: 'ULD-PROB-2026-0004',
    namaLengkap: 'Amanda',
    pin: '123456',
    tanggalLahir: '2016-11-20',
    jenisKelamin: 'P',
    namaWali: 'Rina',
    nomorTelepon: '08977216450',
    alamat: 'Jl. Kapten Pattimura',
    kecamatan: 'Mayangan',
    asalSekolah: 'SDN Mangunharjo 4',
    ragamDisabilitas: 'Terapi Kebutuhan Khusus',
    status: 'aktif',
    terdaftarSejak: '2026-08-01',
    assignedTerapisId: 'terapis-3',
    assignedTerapisNama: 'Salma Salwa Salsabila, S.Pd.',
    assignedAt: '2026-08-01'
  },
  {
    id: 'peserta-05',
    nomorRekamMedis: 'ULD-PROB-2026-0005',
    namaLengkap: 'Arryan Dylan Alfarizqi',
    pin: '123456',
    tanggalLahir: '2017-06-03',
    jenisKelamin: 'L',
    namaWali: 'Siti Zulfa',
    nomorTelepon: '085203050571',
    alamat: 'Dusun Kresek RT 21 RW 04, Desa Sumberbendo',
    kecamatan: 'Luar Kota',
    asalSekolah: 'SLB Sumberbendo',
    ragamDisabilitas: 'Fisioterapi & Motorik Pediatrik',
    status: 'aktif',
    terdaftarSejak: '2026-08-01',
    catatanKhusus: 'Fokus penguatan postur dan ambulasi fisioterapi.',
    assignedTerapisId: 'terapis-2',
    assignedTerapisNama: 'Indaryati Machmudi, A.Md.Kes',
    assignedAt: '2026-08-01'
  },
  {
    id: 'peserta-06',
    nomorRekamMedis: 'ULD-PROB-2026-0006',
    namaLengkap: 'Arsyad Alkhalifi Pradana',
    pin: '123456',
    tanggalLahir: '2018-09-15',
    jenisKelamin: 'L',
    namaWali: 'Adfhitya Oktora Purnomo',
    nomorTelepon: '082334376297',
    alamat: 'Jl. Sunan Bonang 289-298',
    kecamatan: 'Kanigaran',
    asalSekolah: 'MI Syaiful Rizal Kademangan',
    ragamDisabilitas: 'Terapi Perilaku & Sensori',
    status: 'aktif',
    terdaftarSejak: '2026-08-01',
    assignedTerapisId: 'terapis-4',
    assignedTerapisNama: 'Muhammad Ikhsan, M.Psi., Psikolog',
    assignedAt: '2026-08-01'
  },
  {
    id: 'peserta-07',
    nomorRekamMedis: 'ULD-PROB-2026-0007',
    namaLengkap: 'Athafaris Hizam Oktarian',
    pin: '123456',
    tanggalLahir: '2017-05-18',
    jenisKelamin: 'L',
    namaWali: 'Widitri Karunia Oktarina',
    nomorTelepon: '085233112233',
    alamat: 'Jl. Argopuro Kopian Barat',
    kecamatan: 'Kanigaran',
    asalSekolah: 'SDN Ketapang 3',
    ragamDisabilitas: 'Terapi Perilaku & Intervensi Kognitif',
    status: 'aktif',
    terdaftarSejak: '2026-08-01',
    assignedTerapisId: 'terapis-3',
    assignedTerapisNama: 'Salma Salwa Salsabila, S.Pd.',
    assignedAt: '2026-08-01'
  },
  {
    id: 'peserta-08',
    nomorRekamMedis: 'ULD-PROB-2026-0008',
    namaLengkap: 'Athafariz Nazril Khalif',
    pin: '123456',
    tanggalLahir: '2016-12-04',
    jenisKelamin: 'L',
    namaWali: 'Iin Wahyuni',
    nomorTelepon: '085189606299',
    alamat: 'Blok Triwung RT 01 RW 03, Kel. Kademangan',
    kecamatan: 'Kademangan',
    asalSekolah: 'SDN Kademangan 1',
    ragamDisabilitas: 'Terapi Inklusi & PLB',
    status: 'aktif',
    terdaftarSejak: '2026-08-01',
    assignedTerapisId: 'terapis-1',
    assignedTerapisNama: 'Ahmad Hafizul Adly, S.Pd.',
    assignedAt: '2026-08-01'
  },
  {
    id: 'peserta-09',
    nomorRekamMedis: 'ULD-PROB-2026-0009',
    namaLengkap: 'Azfer Farzan Alghifari',
    pin: '123456',
    tanggalLahir: '2018-07-28',
    jenisKelamin: 'L',
    namaWali: 'Indah Afrillia',
    nomorTelepon: '08113146729',
    alamat: 'Jl. Dr. Saleh 5D',
    kecamatan: 'Mayangan',
    asalSekolah: 'SDN Sukabumi 2',
    ragamDisabilitas: 'Terapi Rutin Perilaku',
    status: 'aktif',
    terdaftarSejak: '2026-08-01'
  },
  {
    id: 'peserta-10',
    nomorRekamMedis: 'ULD-PROB-2026-0010',
    namaLengkap: 'Bagas Ardian Pratama',
    pin: '123456',
    tanggalLahir: '2017-03-21',
    jenisKelamin: 'L',
    namaWali: 'Katmiatin',
    nomorTelepon: '082132859280',
    alamat: 'Jl. Priksan Gg. Panda No. 5, Kebonsari Kulon',
    kecamatan: 'Kanigaran',
    asalSekolah: 'SDN Kebonsari Kulon 6',
    ragamDisabilitas: 'Terapi Rutin Sensori & Perilaku',
    status: 'aktif',
    terdaftarSejak: '2026-08-01'
  },
  {
    id: 'peserta-11',
    nomorRekamMedis: 'ULD-PROB-2026-0011',
    namaLengkap: 'Chelsea Zevicia Zainiar',
    pin: '123456',
    tanggalLahir: '2019-10-09',
    jenisKelamin: 'P',
    namaWali: 'Muzayyana',
    nomorTelepon: '085785226924',
    alamat: 'Pohsangit Leres',
    kecamatan: 'Wonoasih',
    asalSekolah: 'TK Assultoniyah',
    ragamDisabilitas: 'Terapi Rutin Tumbuh Kembang',
    status: 'aktif',
    terdaftarSejak: '2026-08-01'
  },
  {
    id: 'peserta-12',
    nomorRekamMedis: 'ULD-PROB-2026-0012',
    namaLengkap: 'Dannish',
    pin: '123456',
    tanggalLahir: '2016-01-17',
    jenisKelamin: 'L',
    namaWali: 'Yunita Sari',
    nomorTelepon: '082333055615',
    alamat: 'Jl. Mayjen Haryono No. 74',
    kecamatan: 'Mayangan',
    asalSekolah: 'SDN Mangunharjo 10',
    ragamDisabilitas: 'Terapi Inklusi Sekolah',
    status: 'aktif',
    terdaftarSejak: '2026-08-01'
  },
  {
    id: 'peserta-13',
    nomorRekamMedis: 'ULD-PROB-2026-0013',
    namaLengkap: 'Dega Maher Al Hisyam',
    pin: '123456',
    tanggalLahir: '2019-04-05',
    jenisKelamin: 'L',
    namaWali: 'Riski Ariska / Risti Arista',
    nomorTelepon: '085335303182',
    alamat: 'Jl. Kyai Maja RT 05 RW 03, Wiroborang',
    kecamatan: 'Mayangan',
    asalSekolah: 'TK Bina Putra Putri',
    ragamDisabilitas: 'Terapi Perilaku & Bicara',
    status: 'aktif',
    terdaftarSejak: '2026-08-01'
  },
  {
    id: 'peserta-14',
    nomorRekamMedis: 'ULD-PROB-2026-0014',
    namaLengkap: 'Dennis',
    pin: '123456',
    tanggalLahir: '2012-08-25',
    jenisKelamin: 'L',
    namaWali: 'Ratih (GPK)',
    nomorTelepon: '081336388876',
    alamat: 'Jl. Hayam Wuruk 155',
    kecamatan: 'Kanigaran',
    asalSekolah: 'SMPN 3 Probolinggo',
    ragamDisabilitas: 'Terapi Pendampingan Inklusi SMP',
    status: 'aktif',
    terdaftarSejak: '2026-08-01'
  },
  {
    id: 'peserta-15',
    nomorRekamMedis: 'ULD-PROB-2026-0015',
    namaLengkap: 'Ergin Pradipta Firmansyah',
    pin: '123456',
    tanggalLahir: '2019-02-11',
    jenisKelamin: 'L',
    namaWali: 'Ayu Wandira / Ach Firmansah',
    nomorTelepon: '085336186487',
    alamat: 'Jl. Gunung Batur Blok Kolor',
    kecamatan: 'Kademangan',
    asalSekolah: 'TK & KB Kemuning',
    ragamDisabilitas: 'Terapi Perilaku & Intervensi Dini',
    status: 'aktif',
    terdaftarSejak: '2026-08-01'
  },
  {
    id: 'peserta-16',
    nomorRekamMedis: 'ULD-PROB-2026-0016',
    namaLengkap: 'Ezhar Putra Budiman',
    pin: '123456',
    tanggalLahir: '2019-06-30',
    jenisKelamin: 'L',
    namaWali: 'Yunita Amiranda',
    nomorTelepon: '085704840170',
    alamat: 'Pohsangit Kidul',
    kecamatan: 'Wonoasih',
    asalSekolah: 'RA Azidan',
    ragamDisabilitas: 'Terapi Tumbuh Kembang',
    status: 'aktif',
    terdaftarSejak: '2026-08-01'
  },
  {
    id: 'peserta-17',
    nomorRekamMedis: 'ULD-PROB-2026-0017',
    namaLengkap: 'Fadiah Keisa S',
    pin: '123456',
    tanggalLahir: '2017-09-14',
    jenisKelamin: 'P',
    namaWali: 'Linda A',
    nomorTelepon: '085189606075',
    alamat: 'Jl. Slamet Riyadi',
    kecamatan: 'Kanigaran',
    asalSekolah: 'SDN Pilang 1',
    ragamDisabilitas: 'Terapi Belajar & Motorik',
    status: 'aktif',
    terdaftarSejak: '2026-08-01'
  },
  {
    id: 'peserta-18',
    nomorRekamMedis: 'ULD-PROB-2026-0018',
    namaLengkap: 'Galang Rizki Ega Pratama',
    pin: '123456',
    tanggalLahir: '2016-07-22',
    jenisKelamin: 'L',
    namaWali: 'Mega Melistya Saptaningrum / Eko',
    nomorTelepon: '081334077962',
    alamat: 'Jl. Wijaya Kusuma No. 64, Sukabumi',
    kecamatan: 'Mayangan',
    asalSekolah: 'SDN Sukabumi 7',
    ragamDisabilitas: 'Terapi Rutin Inklusi',
    status: 'aktif',
    terdaftarSejak: '2026-08-01'
  },
  {
    id: 'peserta-19',
    nomorRekamMedis: 'ULD-PROB-2026-0019',
    namaLengkap: 'Hana Aish Salma Adzra',
    pin: '123456',
    tanggalLahir: '2016-05-10',
    jenisKelamin: 'P',
    namaWali: 'Ekawulandari / Dwi Agus Styawan',
    nomorTelepon: '089679008559',
    alamat: 'Jl. Anggrek No. 16C, Sukabumi',
    kecamatan: 'Mayangan',
    asalSekolah: 'SLB Sinar Harapan 1 / SDLB 1',
    ragamDisabilitas: 'Fisioterapi & Stimulasi Motorik',
    status: 'aktif',
    terdaftarSejak: '2026-08-01',
    catatanKhusus: 'Fokus latihan peregangan & mobilisasi fisik di ruang gimnasium.',
    assignedTerapisId: 'terapis-2',
    assignedTerapisNama: 'Indaryati Machmudi, A.Md.Kes',
    assignedAt: '2026-08-01'
  },
  {
    id: 'peserta-20',
    nomorRekamMedis: 'ULD-PROB-2026-0020',
    namaLengkap: 'Kevin Mavendra Setyawan',
    pin: '123456',
    tanggalLahir: '2016-10-03',
    jenisKelamin: 'L',
    namaWali: 'Ita Putri Purnamasari',
    nomorTelepon: '089678835443',
    alamat: 'Jl. Anggrek No. 10 / Jl. A. Yani Gg. Kahar',
    kecamatan: 'Mayangan',
    asalSekolah: 'SDN Mangunharjo 10',
    ragamDisabilitas: 'Terapi Inklusi Belajar & Konsentrasi',
    status: 'aktif',
    terdaftarSejak: '2026-08-01'
  },
  {
    id: 'peserta-21',
    nomorRekamMedis: 'ULD-PROB-2026-0021',
    namaLengkap: 'M. Arsya As\'adul Kholqi',
    pin: '123456',
    tanggalLahir: '2018-03-12',
    jenisKelamin: 'L',
    namaWali: 'Nurul Hasana',
    nomorTelepon: '085377520647',
    alamat: 'Triwung Kidul',
    kecamatan: 'Kademangan',
    asalSekolah: 'MI Syaifurizal',
    ragamDisabilitas: 'Terapi Rutin Perilaku & Wicara',
    status: 'aktif',
    terdaftarSejak: '2026-08-01'
  },
  {
    id: 'peserta-22',
    nomorRekamMedis: 'ULD-PROB-2026-0022',
    namaLengkap: 'M. Nafi\'',
    pin: '123456',
    tanggalLahir: '2017-08-16',
    jenisKelamin: 'L',
    namaWali: 'Halimatus Sa\'diyah / Muhammad Toha',
    nomorTelepon: '085230374984',
    alamat: 'Jl. KH Gg. Sumbersari, Sukoharjo',
    kecamatan: 'Kanigaran',
    asalSekolah: 'SDN Jati 1',
    ragamDisabilitas: 'Terapi Inklusi & Intervensi Sensori',
    status: 'aktif',
    terdaftarSejak: '2026-08-01'
  },
  {
    id: 'peserta-23',
    nomorRekamMedis: 'ULD-PROB-2026-0023',
    namaLengkap: 'M. Najih',
    pin: '123456',
    tanggalLahir: '2017-11-29',
    jenisKelamin: 'L',
    namaWali: 'Utami Ningsih',
    nomorTelepon: '085236191701',
    alamat: 'Jl. Slamet Riyadi',
    kecamatan: 'Kanigaran',
    asalSekolah: 'MI Syaifurizal',
    ragamDisabilitas: 'Terapi Perilaku & Belajar',
    status: 'aktif',
    terdaftarSejak: '2026-08-01'
  },
  {
    id: 'peserta-24',
    nomorRekamMedis: 'ULD-PROB-2026-0024',
    namaLengkap: 'Meycyla Esa Yuanindya',
    pin: '123456',
    tanggalLahir: '2012-05-08',
    jenisKelamin: 'P',
    namaWali: 'Yeni Meisa / Gilang Teguh',
    nomorTelepon: '082228999009',
    alamat: 'Perum Hidayah No. 8, Mangunharjo',
    kecamatan: 'Mayangan',
    asalSekolah: 'SMP Muhammadiyah 1 Probolinggo',
    ragamDisabilitas: 'Terapi Perkembangan Remaja Inklusi',
    status: 'aktif',
    terdaftarSejak: '2026-08-01'
  },
  {
    id: 'peserta-25',
    nomorRekamMedis: 'ULD-PROB-2026-0025',
    namaLengkap: 'Mikhayla Anggraeni Mubarok',
    pin: '123456',
    tanggalLahir: '2017-09-02',
    jenisKelamin: 'P',
    namaWali: 'Husni Mubarok',
    nomorTelepon: '085236656664',
    alamat: 'Jl. Anggur RT 01 RW 01, Wonoasih',
    kecamatan: 'Wonoasih',
    asalSekolah: 'SDN Kedopok 1',
    ragamDisabilitas: 'Terapi Inklusi & Stimulasi Kognitif',
    status: 'aktif',
    terdaftarSejak: '2026-08-01'
  },
  {
    id: 'peserta-26',
    nomorRekamMedis: 'ULD-PROB-2026-0026',
    namaLengkap: 'Mirza Dana Arrosyid',
    pin: '123456',
    tanggalLahir: '2018-04-18',
    jenisKelamin: 'L',
    namaWali: 'Lidya Novita Sandy',
    nomorTelepon: '085290775753',
    alamat: 'Jl. Anggrek Kuning Gg. 1',
    kecamatan: 'Mayangan',
    asalSekolah: 'MI Syaiful Rizal',
    ragamDisabilitas: 'Fisioterapi & Terapi Gerak',
    status: 'aktif',
    terdaftarSejak: '2026-08-01'
  },
  {
    id: 'peserta-27',
    nomorRekamMedis: 'ULD-PROB-2026-0027',
    namaLengkap: 'Muhammad Abdillah',
    pin: '123456',
    tanggalLahir: '2016-12-19',
    jenisKelamin: 'L',
    namaWali: 'Meri Sandra Dewi / Handayani',
    nomorTelepon: '085211223344',
    alamat: 'Jl. Gatot Subroto No. 122',
    kecamatan: 'Kanigaran',
    asalSekolah: 'ATS',
    ragamDisabilitas: 'Terapi Perilaku & Intervensi Terarah',
    status: 'aktif',
    terdaftarSejak: '2026-08-01'
  },
  {
    id: 'peserta-28',
    nomorRekamMedis: 'ULD-PROB-2026-0028',
    namaLengkap: 'Muhammad Farrel',
    pin: '123456',
    tanggalLahir: '2019-01-23',
    jenisKelamin: 'L',
    namaWali: 'Dedik / Dedi / Yanti',
    nomorTelepon: '085257407486',
    alamat: 'Jl. PO Nusantara',
    kecamatan: 'Mayangan',
    asalSekolah: 'TK Kemuning Mayangan',
    ragamDisabilitas: 'Terapi Rutin Anak Usia Dini',
    status: 'aktif',
    terdaftarSejak: '2026-08-01'
  },
  {
    id: 'peserta-29',
    nomorRekamMedis: 'ULD-PROB-2026-0029',
    namaLengkap: 'Muhammad Fikri Abdillah',
    pin: '123456',
    tanggalLahir: '2017-04-14',
    jenisKelamin: 'L',
    namaWali: 'Husnul Chotimah',
    nomorTelepon: '085177295955',
    alamat: 'Dusun Manis 2, Laweyan Sumberasih',
    kecamatan: 'Luar Kota',
    asalSekolah: 'MI Ihyaul Islam',
    ragamDisabilitas: 'Terapi Calistung & Remedial Kognitif',
    status: 'aktif',
    terdaftarSejak: '2026-08-01'
  },
  {
    id: 'peserta-30',
    nomorRekamMedis: 'ULD-PROB-2026-0030',
    namaLengkap: 'Muhammad Gafi Jabarullah',
    pin: '123456',
    tanggalLahir: '2019-07-06',
    jenisKelamin: 'L',
    namaWali: 'Amelia',
    nomorTelepon: '082136685007',
    alamat: 'Jl. Mastrip Perum Diva Dava 2 No. 02',
    kecamatan: 'Kanigaran',
    asalSekolah: 'TK Namira',
    ragamDisabilitas: 'Terapi Perilaku & Sensori',
    status: 'aktif',
    terdaftarSejak: '2026-08-01'
  },
  {
    id: 'peserta-31',
    nomorRekamMedis: 'ULD-PROB-2026-0031',
    namaLengkap: 'Muhammad Gufron Firmansyah',
    pin: '123456',
    tanggalLahir: '2016-08-30',
    jenisKelamin: 'L',
    namaWali: 'Siti Romlah',
    nomorTelepon: '082142582701',
    alamat: 'Jl. Raya Panglima Sudirman Gg. PJKA No. 70',
    kecamatan: 'Kanigaran',
    asalSekolah: 'SDN Kebonsari Kulon 6',
    ragamDisabilitas: 'Terapi Calistung & Konsentrasi Belajar',
    status: 'aktif',
    terdaftarSejak: '2026-08-01'
  },
  {
    id: 'peserta-32',
    nomorRekamMedis: 'ULD-PROB-2026-0032',
    namaLengkap: 'Muhammad Ilham Dwi Yungga',
    pin: '123456',
    tanggalLahir: '2018-12-11',
    jenisKelamin: 'L',
    namaWali: 'Enggar Prastiwi',
    nomorTelepon: '085330054710',
    alamat: 'Perum Himalaya Gg. 2a No. 11',
    kecamatan: 'Kedopok',
    asalSekolah: 'RA / TK Inklusi Azidan',
    ragamDisabilitas: 'Terapi Perilaku & Intervensi Inklusi',
    status: 'aktif',
    terdaftarSejak: '2026-08-01'
  },
  {
    id: 'peserta-33',
    nomorRekamMedis: 'ULD-PROB-2026-0033',
    namaLengkap: 'Muhammad Izza Danar Hidayat',
    pin: '123456',
    tanggalLahir: '2017-03-05',
    jenisKelamin: 'L',
    namaWali: 'Yuliatin',
    nomorTelepon: '081331516923',
    alamat: 'Jl. Citarum Perum D\'sultan Regency',
    kecamatan: 'Kanigaran',
    asalSekolah: 'MI Syaifurizal',
    ragamDisabilitas: 'Terapi Perilaku (Behavior Therapy)',
    status: 'aktif',
    terdaftarSejak: '2026-08-01'
  },
  {
    id: 'peserta-34',
    nomorRekamMedis: 'ULD-PROB-2026-0034',
    namaLengkap: 'Muhammad Putra Azlan Syarahil',
    pin: '123456',
    tanggalLahir: '2019-09-17',
    jenisKelamin: 'L',
    namaWali: 'Dita Indriyani',
    nomorTelepon: '089510237426',
    alamat: 'Jl. Kapten Pattimura Gg. Tajungan RT 02 RW 08',
    kecamatan: 'Mayangan',
    asalSekolah: 'KB / TK Kemuning',
    ragamDisabilitas: 'Terapi Rutin Perilaku & Sensori',
    status: 'aktif',
    terdaftarSejak: '2026-08-01'
  },
  {
    id: 'peserta-35',
    nomorRekamMedis: 'ULD-PROB-2026-0035',
    namaLengkap: 'Muhammad Ridho Rohman',
    pin: '123456',
    tanggalLahir: '2018-05-24',
    jenisKelamin: 'L',
    namaWali: 'Nur Puji Astutik',
    nomorTelepon: '085231693301',
    alamat: 'Jl. Cokroaminoto Gg. Siam No. 54-56',
    kecamatan: 'Kanigaran',
    asalSekolah: 'TK / KB Kemuning',
    ragamDisabilitas: 'Terapi Rutin Wicara & Perilaku',
    status: 'aktif',
    terdaftarSejak: '2026-08-01'
  },
  {
    id: 'peserta-36',
    nomorRekamMedis: 'ULD-PROB-2026-0036',
    namaLengkap: 'Naufal Arvano Darma',
    pin: '123456',
    tanggalLahir: '2018-08-07',
    jenisKelamin: 'L',
    namaWali: 'Nurul Hamidah',
    nomorTelepon: '082337315458',
    alamat: 'Jl. Kerinci Perum Rangga Permai, Pilang',
    kecamatan: 'Kademangan',
    asalSekolah: 'TK Kemuning',
    ragamDisabilitas: 'Terapi Perilaku (Behavior Therapy)',
    status: 'aktif',
    terdaftarSejak: '2026-08-01'
  },
  {
    id: 'peserta-37',
    nomorRekamMedis: 'ULD-PROB-2026-0037',
    namaLengkap: 'Nehad Ubay',
    pin: '123456',
    tanggalLahir: '2019-11-13',
    jenisKelamin: 'L',
    namaWali: 'Amnarul Jihad / Amna',
    nomorTelepon: '082337995221',
    alamat: 'Jl. Kapten Pattimura No. 29',
    kecamatan: 'Mayangan',
    asalSekolah: 'KB / PAUD Kemuning',
    ragamDisabilitas: 'Terapi Mingguan Terpadu',
    status: 'aktif',
    terdaftarSejak: '2026-08-01'
  },
  {
    id: 'peserta-38',
    nomorRekamMedis: 'ULD-PROB-2026-0038',
    namaLengkap: 'Raffisky',
    pin: '123456',
    tanggalLahir: '2019-03-01',
    jenisKelamin: 'L',
    namaWali: 'Desy / Desi M',
    nomorTelepon: '0895393158096',
    alamat: 'Jl. Cokroaminoto Gg. Listrikan No. 232',
    kecamatan: 'Kanigaran',
    asalSekolah: 'TK Bintang',
    ragamDisabilitas: 'Terapi Perilaku & Intervensi Kognitif',
    status: 'aktif',
    terdaftarSejak: '2026-08-01'
  },
  {
    id: 'peserta-39',
    nomorRekamMedis: 'ULD-PROB-2026-0039',
    namaLengkap: 'Rahayu',
    pin: '123456',
    tanggalLahir: '2018-06-18',
    jenisKelamin: 'P',
    namaWali: 'Yayah Rokayah',
    nomorTelepon: '082131218444',
    alamat: 'Triwung Kidul',
    kecamatan: 'Kademangan',
    asalSekolah: 'RA Azidan',
    ragamDisabilitas: 'Terapi Tumbuh Kembang Inklusif',
    status: 'aktif',
    terdaftarSejak: '2026-08-01'
  },
  {
    id: 'peserta-40',
    nomorRekamMedis: 'ULD-PROB-2026-0040',
    namaLengkap: 'Rahsya',
    pin: '123456',
    tanggalLahir: '2018-10-27',
    jenisKelamin: 'L',
    namaWali: 'Faris Hamzah',
    nomorTelepon: '085235592729',
    alamat: 'Jl. Ikan Dorang No. 16',
    kecamatan: 'Mayangan',
    asalSekolah: 'TK Kemuning',
    ragamDisabilitas: 'Terapi Rutin Perilaku',
    status: 'aktif',
    terdaftarSejak: '2026-08-01'
  },
  {
    id: 'peserta-41',
    nomorRekamMedis: 'ULD-PROB-2026-0041',
    namaLengkap: 'Revan',
    pin: '123456',
    tanggalLahir: '2012-09-04',
    jenisKelamin: 'L',
    namaWali: 'Ratih (GPK)',
    nomorTelepon: '081336388876',
    alamat: 'Sukoharjo',
    kecamatan: 'Kanigaran',
    asalSekolah: 'SMPN 3 Probolinggo',
    ragamDisabilitas: 'Terapi Inklusi & Adaptasi Sosial',
    status: 'aktif',
    terdaftarSejak: '2026-08-01'
  },
  {
    id: 'peserta-42',
    nomorRekamMedis: 'ULD-PROB-2026-0042',
    namaLengkap: 'Reyhan Kenzie Putra Ashfaro',
    pin: '123456',
    tanggalLahir: '2017-01-20',
    jenisKelamin: 'L',
    namaWali: 'Rinaldy Aliandi Mukhtar / Dian Nur Wulandari',
    nomorTelepon: '085337578234',
    alamat: 'Jl. Bengawan Solo No. 14, Jrebeng Wetan',
    kecamatan: 'Kedopok',
    asalSekolah: 'SDN Kedopok 1',
    ragamDisabilitas: 'Terapi Inklusi & Intervensi Kognitif',
    status: 'aktif',
    terdaftarSejak: '2026-08-01'
  },
  {
    id: 'peserta-43',
    nomorRekamMedis: 'ULD-PROB-2026-0043',
    namaLengkap: 'Safea Rizki Elzain',
    pin: '123456',
    tanggalLahir: '2017-10-15',
    jenisKelamin: 'P',
    namaWali: 'Ilmi Musayadah',
    nomorTelepon: '081230137311',
    alamat: 'Jl. Slamet Riyadi Gg. 1 No. 53',
    kecamatan: 'Kanigaran',
    asalSekolah: 'MI Hidayat',
    ragamDisabilitas: 'Terapi Belajar & Perilaku',
    status: 'aktif',
    terdaftarSejak: '2026-08-01'
  },
  {
    id: 'peserta-44',
    nomorRekamMedis: 'ULD-PROB-2026-0044',
    namaLengkap: 'Sandi Agus Saputra',
    pin: '123456',
    tanggalLahir: '2016-04-09',
    jenisKelamin: 'L',
    namaWali: 'Eni Hartatik',
    nomorTelepon: '082133825082',
    alamat: 'Jl. Brantas / Tambora RT 06 RW 02',
    kecamatan: 'Kademangan',
    asalSekolah: 'SDN Kademangan 1',
    ragamDisabilitas: 'Terapi Inklusi Sekolah',
    status: 'aktif',
    terdaftarSejak: '2026-08-01'
  },
  {
    id: 'peserta-45',
    nomorRekamMedis: 'ULD-PROB-2026-0045',
    namaLengkap: 'Shafa Aisyah & Marwah Az Zahra',
    pin: '123456',
    tanggalLahir: '2018-01-11',
    jenisKelamin: 'P',
    namaWali: 'Hadi Ali Sandi',
    nomorTelepon: '082150384106',
    alamat: 'Mentor, Sumberasih',
    kecamatan: 'Luar Kota',
    asalSekolah: 'MI Saifurrizal Kademangan',
    ragamDisabilitas: 'Terapi Tumbuh Kembang (Kembar)',
    status: 'aktif',
    terdaftarSejak: '2026-08-01'
  },
  {
    id: 'peserta-46',
    nomorRekamMedis: 'ULD-PROB-2026-0046',
    namaLengkap: 'Uwais',
    pin: '123456',
    tanggalLahir: '2018-08-20',
    jenisKelamin: 'L',
    namaWali: 'Widia Amelia / Siti Mutia Maisaroh',
    nomorTelepon: '082257154080',
    alamat: 'Jl. KH Fadhol / Sepuh Gembol',
    kecamatan: 'Wonoasih',
    asalSekolah: 'MI Saifuridzal',
    ragamDisabilitas: 'Terapi Perilaku & Intervensi',
    status: 'aktif',
    terdaftarSejak: '2026-08-01'
  },
  {
    id: 'peserta-47',
    nomorRekamMedis: 'ULD-PROB-2026-0047',
    namaLengkap: 'Wildan Ulil Albab',
    pin: '123456',
    tanggalLahir: '2016-09-08',
    jenisKelamin: 'L',
    namaWali: 'Sella',
    nomorTelepon: '0895325875194',
    alamat: 'Jl. Basuki Rahmat No. 18',
    kecamatan: 'Mayangan',
    asalSekolah: 'SDN Mangunharjo 10',
    ragamDisabilitas: 'Fisioterapi & Motorik Inklusi',
    status: 'aktif',
    terdaftarSejak: '2026-08-01'
  },
  {
    id: 'peserta-48',
    nomorRekamMedis: 'ULD-PROB-2026-0048',
    namaLengkap: 'Zaqi Anugrah Firdaus',
    pin: '123456',
    tanggalLahir: '2016-06-15',
    jenisKelamin: 'L',
    namaWali: 'Devi Harianti',
    nomorTelepon: '0895329317440',
    alamat: 'Jl. KH Mansyur Gg. 7 / Patiunus',
    kecamatan: 'Mayangan',
    asalSekolah: 'SDN Mangunharjo 10',
    ragamDisabilitas: 'Terapi Rutin Belajar & Perilaku',
    status: 'aktif',
    terdaftarSejak: '2026-08-01'
  }
];

export const INITIAL_SLOTS: SlotHarian[] = [
  // Senin - Jumat Sesi 09.00 - 13.00
  {
    id: 'slot-1',
    terapisId: 'terapis-1', // Ahmad Hafizul Adly (Terapis Perilaku)
    tanggal: getNextWeekdayDate(0),
    jamMulai: '09:00',
    jamSelesai: '10:00',
    spesialisasi: 'terapis_perilaku',
    ruang: 'Ruang Terapi Perilaku & Sensori 1',
    kuotaMaksimal: 1,
    kuotaTerisi: 1,
    catatanTerapis: 'Fokus: Pembiasaan instruksi & kontak mata.',
    statusSlot: 'penuh',
    createdAt: new Date().toISOString()
  },
  {
    id: 'slot-2',
    terapisId: 'terapis-1', // Ahmad Hafizul Adly (Terapis Perilaku)
    tanggal: getNextWeekdayDate(0),
    jamMulai: '10:00',
    jamSelesai: '11:00',
    spesialisasi: 'terapis_perilaku',
    ruang: 'Ruang Terapi Perilaku & Sensori 1',
    kuotaMaksimal: 1,
    kuotaTerisi: 0,
    catatanTerapis: 'Bawa mainan atau camilan favorit anak.',
    statusSlot: 'tersedia',
    createdAt: new Date().toISOString()
  },
  {
    id: 'slot-3',
    terapisId: 'terapis-2', // Indaryati Machmudi (Fisioterapis)
    tanggal: getNextWeekdayDate(0),
    jamMulai: '09:00',
    jamSelesai: '10:00',
    spesialisasi: 'fisioterapis',
    ruang: 'Ruang Fisioterapi Gimnasium Inklusif',
    kuotaMaksimal: 1,
    kuotaTerisi: 1,
    catatanTerapis: 'Stimulasi motorik & postur tubuh.',
    statusSlot: 'penuh',
    createdAt: new Date().toISOString()
  },
  {
    id: 'slot-4',
    terapisId: 'terapis-2', // Indaryati Machmudi (Fisioterapis)
    tanggal: getNextWeekdayDate(0),
    jamMulai: '11:00',
    jamSelesai: '12:00',
    spesialisasi: 'fisioterapis',
    ruang: 'Ruang Fisioterapi Gimnasium Inklusif',
    kuotaMaksimal: 1,
    kuotaTerisi: 0,
    catatanTerapis: 'Pakaian kaos dan celana olahraga lentur.',
    statusSlot: 'tersedia',
    createdAt: new Date().toISOString()
  },
  {
    id: 'slot-5',
    terapisId: 'terapis-3', // Salma Salwa Salsabila (Tenaga PLB)
    tanggal: getNextWeekdayDate(1),
    jamMulai: '09:00',
    jamSelesai: '10:00',
    spesialisasi: 'tenaga_plb',
    ruang: 'Ruang Edukasi & Remedial PLB',
    kuotaMaksimal: 1,
    kuotaTerisi: 0,
    catatanTerapis: 'Kesiapan sekolah & pengenalan simbol visual.',
    statusSlot: 'tersedia',
    createdAt: new Date().toISOString()
  },
  {
    id: 'slot-6',
    terapisId: 'terapis-3', // Salma Salwa Salsabila (Tenaga PLB)
    tanggal: getNextWeekdayDate(1),
    jamMulai: '10:00',
    jamSelesai: '11:00',
    spesialisasi: 'tenaga_plb',
    ruang: 'Ruang Edukasi & Remedial PLB',
    kuotaMaksimal: 1,
    kuotaTerisi: 0,
    catatanTerapis: 'Program latihan konsentrasi terstruktur.',
    statusSlot: 'tersedia',
    createdAt: new Date().toISOString()
  },
  {
    id: 'slot-7',
    terapisId: 'terapis-4', // Muhammad Ikhsan (Psikolog)
    tanggal: getNextWeekdayDate(1),
    jamMulai: '10:00',
    jamSelesai: '11:30',
    spesialisasi: 'psikolog',
    ruang: 'Ruang Konsultasi & Observasi Psikologi',
    kuotaMaksimal: 1,
    kuotaTerisi: 0,
    catatanTerapis: 'Sesi evaluasi perkembangan dan konseling orang tua.',
    statusSlot: 'tersedia',
    createdAt: new Date().toISOString()
  },
  {
    id: 'slot-8',
    terapisId: 'terapis-4', // Muhammad Ikhsan (Psikolog)
    tanggal: getNextWeekdayDate(1),
    jamMulai: '11:30',
    jamSelesai: '13:00',
    spesialisasi: 'psikolog',
    ruang: 'Ruang Konsultasi & Observasi Psikologi',
    kuotaMaksimal: 1,
    kuotaTerisi: 0,
    catatanTerapis: 'Konsultasi pengasuhan ramah disabilitas.',
    statusSlot: 'tersedia',
    createdAt: new Date().toISOString()
  },
  {
    id: 'slot-9',
    terapisId: 'terapis-1', // Ahmad Hafizul Adly (Terapis Perilaku)
    tanggal: getNextWeekdayDate(2),
    jamMulai: '11:00',
    jamSelesai: '12:00',
    spesialisasi: 'terapis_perilaku',
    ruang: 'Ruang Terapi Perilaku & Sensori 1',
    kuotaMaksimal: 1,
    kuotaTerisi: 0,
    catatanTerapis: 'Regulasi emosi & kepatuhan.',
    statusSlot: 'tersedia',
    createdAt: new Date().toISOString()
  },
  {
    id: 'slot-10',
    terapisId: 'terapis-2', // Indaryati Machmudi (Fisioterapis)
    tanggal: getNextWeekdayDate(2),
    jamMulai: '12:00',
    jamSelesai: '13:00',
    spesialisasi: 'fisioterapis',
    ruang: 'Ruang Fisioterapi Gimnasium Inklusif',
    kuotaMaksimal: 1,
    kuotaTerisi: 0,
    catatanTerapis: 'Latihan penguatan sendi & mobilitas.',
    statusSlot: 'tersedia',
    createdAt: new Date().toISOString()
  },
  {
    id: 'slot-11',
    terapisId: 'terapis-1', // Ahmad Hafizul Adly (Terapis Perilaku)
    tanggal: getNextWeekdayDate(1),
    jamMulai: '09:00',
    jamSelesai: '10:00',
    spesialisasi: 'terapis_perilaku',
    ruang: 'Ruang Terapi Perilaku & Sensori 1',
    kuotaMaksimal: 1,
    kuotaTerisi: 0,
    catatanTerapis: 'Sesi latihan kepatuhan dan kontak mata.',
    statusSlot: 'tersedia',
    createdAt: new Date().toISOString()
  },
  {
    id: 'slot-12',
    terapisId: 'terapis-2', // Indaryati Machmudi (Fisioterapis)
    tanggal: getNextWeekdayDate(1),
    jamMulai: '10:00',
    jamSelesai: '11:00',
    spesialisasi: 'fisioterapis',
    ruang: 'Ruang Fisioterapi Gimnasium Inklusif',
    kuotaMaksimal: 1,
    kuotaTerisi: 0,
    catatanTerapis: 'Stimulasi motorik kasar dan keseimbangan tubuh.',
    statusSlot: 'tersedia',
    createdAt: new Date().toISOString()
  },
  {
    id: 'slot-13',
    terapisId: 'terapis-3', // Salma Salwa Salsabila (Tenaga PLB)
    tanggal: getNextWeekdayDate(2),
    jamMulai: '09:00',
    jamSelesai: '10:00',
    spesialisasi: 'tenaga_plb',
    ruang: 'Ruang Edukasi & Remedial PLB',
    kuotaMaksimal: 1,
    kuotaTerisi: 0,
    catatanTerapis: 'Latihan pra-akademik & fokus belajar anak.',
    statusSlot: 'tersedia',
    createdAt: new Date().toISOString()
  },
  {
    id: 'slot-14',
    terapisId: 'terapis-4', // Muhammad Ikhsan (Psikolog)
    tanggal: getNextWeekdayDate(2),
    jamMulai: '10:00',
    jamSelesai: '11:30',
    spesialisasi: 'psikolog',
    ruang: 'Ruang Konsultasi & Observasi Psikologi',
    kuotaMaksimal: 1,
    kuotaTerisi: 0,
    catatanTerapis: 'Konseling psikologi tumbuh kembang anak inklusi.',
    statusSlot: 'tersedia',
    createdAt: new Date().toISOString()
  }
];

export const INITIAL_BOOKINGS: BookingTerapi[] = [
  {
    id: 'booking-1',
    slotId: 'slot-1',
    pesertaId: 'peserta-01', // Abimanyu Tri Yoga
    terapisId: 'terapis-1',
    kodeBooking: 'TRP-2026-081',
    tanggal: getNextWeekdayDate(0),
    jamMulai: '09:00',
    jamSelesai: '10:00',
    spesialisasi: 'terapis_perilaku',
    ruang: 'Ruang Terapi Perilaku & Sensori 1',
    status: 'terjadwal',
    keluhanHariIni: 'Fokus konsentrasi dan pengurangan distraksi.',
    createdAt: new Date().toISOString()
  },
  {
    id: 'booking-2',
    slotId: 'slot-3',
    pesertaId: 'peserta-19', // Hana Aish Salma Adzra
    terapisId: 'terapis-2',
    kodeBooking: 'TRP-2026-082',
    tanggal: getNextWeekdayDate(0),
    jamMulai: '09:00',
    jamSelesai: '10:00',
    spesialisasi: 'fisioterapis',
    ruang: 'Ruang Fisioterapi Gimnasium Inklusif',
    status: 'terjadwal',
    keluhanHariIni: 'Latihan penegakan tumit dan peregangan hamstring.',
    createdAt: new Date().toISOString()
  }
];

export const INITIAL_ASESMEN_GUEST: PendaftaranAsesmenGuest[] = [
  {
    id: 'guest-asm-1',
    nomorRegistrasi: 'ASM-PROB-2026-0034',
    namaAnak: 'Althaf Nizam Prasetyo',
    tanggalLahir: '2021-03-10',
    jenisKelamin: 'L',
    namaOrangTua: 'Hendra Prasetyo',
    nikAnakOrKK: '3574011003210002',
    nomorWhatsApp: '081298765432',
    alamatDomisili: 'Jl. Srikandi No. 18, RT 01 / RW 02',
    kecamatan: 'Wonoasih',
    jenjangPendidikan: 'PAUD/TK',
    asalSekolah: 'TK Bina Putra Putri Kota Probolinggo',
    nisnOrNpsn: '3210058471',
    sudahTerdaftarDapodik: true,
    indikasiAwal: 'Speech delay, belum merespons saat dipanggil nama, kontak mata minim.',
    dokumenAkanDibawa: ['Kartu Keluarga (KK)', 'KTP Orang Tua/Wali', 'Buku KIA Pink', 'Surat Rujukan Puskesmas', 'Bukti Terdaftar DAPODIK'],
    tanggalRencanaDatang: getNextWeekdayDate(1),
    jamRencanaDatang: '09:00 WIB',
    status: 'menunggu_verifikasi_fisik',
    catatanPetugas: 'Ditunggu kedatangan di Gedung ULD Lt. 1 Loket Registrasi.',
    createdAt: new Date().toISOString()
  },
  {
    id: 'guest-asm-2',
    nomorRegistrasi: 'ASM-PROB-2026-0035',
    namaAnak: 'Zalfa Naura Putri',
    tanggalLahir: '2020-07-19',
    jenisKelamin: 'P',
    namaOrangTua: 'Ratna Susanti',
    nikAnakOrKK: '3574025907220005',
    nomorWhatsApp: '085811223344',
    alamatDomisili: 'Jl. Ikan Kerapu No. 8',
    kecamatan: 'Mayangan',
    jenjangPendidikan: 'PAUD/TK',
    asalSekolah: 'TK Kemuning Mayangan',
    nisnOrNpsn: '3200984712',
    sudahTerdaftarDapodik: true,
    indikasiAwal: 'Keterlambatan motorik kasar (belum bisa jalan mandiri pada usia 2 tahun lebih).',
    dokumenAkanDibawa: ['Kartu Keluarga (KK)', 'KTP Orang Tua/Wali', 'Buku KIA Pink', 'Bukti Terdaftar DAPODIK'],
    tanggalRencanaDatang: getNextWeekdayDate(2),
    jamRencanaDatang: '10:00 WIB',
    status: 'menunggu_verifikasi_fisik',
    catatanPetugas: 'Persiapkan berkas fotokopi 2 rangkap.',
    createdAt: new Date().toISOString()
  }
];
